# Generated by Django 2.0.6 on 2018-06-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20180630_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='name',
            new_name='zip_code',
        ),
    ]
