# Generated by Django 2.0.6 on 2018-06-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180623_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.Country'),
            preserve_default=False,
        ),
    ]
